# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

##### CARD DECK TEMPLATE ######
Deck.create(id: 1, card: 'Ace', suite: 'clubs')
Deck.create(id: 2, card: '2', suite: 'clubs')
Deck.create(id: 3, card: '3', suite: 'clubs')
Deck.create(id: 4, card: '4', suite: 'clubs')
Deck.create(id: 5, card: '5', suite: 'clubs')
Deck.create(id: 6, card: '6', suite: 'clubs')
Deck.create(id: 7, card: '7', suite: 'clubs')
Deck.create(id: 8, card: '8', suite: 'clubs')
Deck.create(id: 9, card: '9', suite: 'clubs')
Deck.create(id: 10, card: '10', suite: 'clubs')
Deck.create(id: 11, card: 'Jack', suite: 'clubs')
Deck.create(id: 12, card: 'Queen', suite: 'clubs')
Deck.create(id: 13, card: 'King', suite: 'clubs')
Deck.create(id: 14, card: 'Ace', suite: 'diamonds')
Deck.create(id: 15, card: '2', suite: 'diamonds')
Deck.create(id: 16, card: '3', suite: 'diamonds')
Deck.create(id: 17, card: '4', suite: 'diamonds')
Deck.create(id: 18, card: '5', suite: 'diamonds')
Deck.create(id: 19, card: '6', suite: 'diamonds')
Deck.create(id: 20, card: '7', suite: 'diamonds')
Deck.create(id: 21, card: '8', suite: 'diamonds')
Deck.create(id: 22, card: '9', suite: 'diamonds')
Deck.create(id: 23, card: '10', suite: 'diamonds')
Deck.create(id: 24, card: 'Jack', suite: 'diamonds')
Deck.create(id: 25, card: 'Queen', suite: 'diamonds')
Deck.create(id: 26, card: 'King', suite: 'diamonds')
Deck.create(id: 27, card: 'Ace', suite: 'hearts')
Deck.create(id: 28, card: '2', suite: 'hearts')
Deck.create(id: 29, card: '3', suite: 'hearts')
Deck.create(id: 30, card: '4', suite: 'hearts')
Deck.create(id: 31, card: '5', suite: 'hearts')
Deck.create(id: 32, card: '6', suite: 'hearts')
Deck.create(id: 33, card: '7', suite: 'hearts')
Deck.create(id: 34, card: '8', suite: 'hearts')
Deck.create(id: 35, card: '9', suite: 'hearts')
Deck.create(id: 36, card: '10', suite: 'hearts')
Deck.create(id: 37, card: 'Jack', suite: 'hearts')
Deck.create(id: 38, card: 'Queen', suite: 'hearts')
Deck.create(id: 39, card: 'King', suite: 'hearts')
Deck.create(id: 40, card: 'Ace', suite: 'spades')
Deck.create(id: 41, card: '2', suite: 'spades')
Deck.create(id: 42, card: '3', suite: 'spades')
Deck.create(id: 43, card: '4', suite: 'spades')
Deck.create(id: 44, card: '5', suite: 'spades')
Deck.create(id: 45, card: '6', suite: 'spades')
Deck.create(id: 46, card: '7', suite: 'spades')
Deck.create(id: 47, card: '8', suite: 'spades')
Deck.create(id: 48, card: '9', suite: 'spades')
Deck.create(id: 49, card: '10', suite: 'spades')
Deck.create(id: 50, card: 'Jack', suite: 'spades')
Deck.create(id: 51, card: 'Queen', suite: 'spades')
Deck.create(id: 52, card: 'King', suite: 'spades')


##### CARD Rule ######
Hand.create(id: 1, hand: 'Single')
Hand.create(id: 2, hand: 'Pair')
Hand.create(id: 3, hand: 'Two Pair')
Hand.create(id: 5, hand: 'Three of a kind')
Hand.create(id: 6, hand: 'Straight')
Hand.create(id: 7, hand: 'Full House')
Hand.create(id: 8, hand: 'Four of a kind')
Hand.create(id: 9, hand: 'Straight Flush')
